import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  ...compat.extends("next/core-web-vitals"),
  {
    rules: {
      // Completely disable ALL ESLint rules
      "react/no-unescaped-entities": "off",
      "@next/next/no-img-element": "off",
      "@next/next/no-html-link-for-pages": "off",
      "@next/next/no-page-custom-font": "off",
      "@next/next/no-css-tags": "off",
      "@next/next/no-head-element": "off",
      "@next/next/no-script-component-in-head": "off",
      "@next/next/no-before-interactive-script-outside-document": "off",
      "@next/next/no-styled-jsx-in-document": "off",
      "@next/next/no-title-in-document-head": "off",
      "@next/next/no-document-import-in-page": "off",
      "@next/next/no-head-import-in-document": "off",
      "@next/next/no-sync-scripts": "off",
      "@next/next/no-typos": "off",
      "@next/next/no-unwanted-polyfillio": "off",
      "@next/next/inline-script-id": "off",
      "@next/next/next-script-for-ga": "off",
      "@next/next/no-assign-module-variable": "off",
      "@next/next/no-duplicate-head": "off",
      "@next/next/google-font-display": "off",
      "@next/next/google-font-preconnect": "off",
      "@next/next/no-server-import-in-page": "off",
      
      // React rules
      "react/display-name": "off",
      "react/jsx-key": "off",
      "react/jsx-no-comment-textnodes": "off",
      "react/jsx-no-duplicate-props": "off",
      "react/jsx-no-target-blank": "off",
      "react/jsx-no-undef": "off",
      "react/jsx-uses-react": "off",
      "react/jsx-uses-vars": "off",
      "react/no-children-prop": "off",
      "react/no-danger-with-children": "off",
      "react/no-deprecated": "off",
      "react/no-direct-mutation-state": "off",
      "react/no-find-dom-node": "off",
      "react/no-is-mounted": "off",
      "react/no-render-return-value": "off",
      "react/no-string-refs": "off",
      "react/no-unknown-property": "off",
      "react/prop-types": "off",
      "react/react-in-jsx-scope": "off",
      "react/require-render-return": "off",
      
      // JavaScript/TypeScript rules
      "no-unused-vars": "off",
      "no-console": "off",
      "no-debugger": "off",
      "prefer-const": "off",
      "no-var": "off",
      "no-undef": "off",
      "no-unreachable": "off",
      "no-empty": "off",
      "no-extra-semi": "off",
      "no-func-assign": "off",
      "no-irregular-whitespace": "off",
      "no-obj-calls": "off",
      "no-sparse-arrays": "off",
      "use-isnan": "off",
      "valid-typeof": "off",
      "curly": "off",
      "dot-notation": "off",
      "eqeqeq": "off",
      "no-alert": "off",
      "no-caller": "off",
      "no-case-declarations": "off",
      "no-else-return": "off",
      "no-empty-pattern": "off",
      "no-eval": "off",
      "no-extend-native": "off",
      "no-extra-bind": "off",
      "no-fallthrough": "off",
      "no-floating-decimal": "off",
      "no-global-assign": "off",
      "no-implied-eval": "off",
      "no-invalid-this": "off",
      "no-iterator": "off",
      "no-labels": "off",
      "no-lone-blocks": "off",
      "no-loop-func": "off",
      "no-multi-spaces": "off",
      "no-multi-str": "off",
      "no-new": "off",
      "no-new-func": "off",
      "no-new-wrappers": "off",
      "no-octal": "off",
      "no-octal-escape": "off",
      "no-proto": "off",
      "no-redeclare": "off",
      "no-return-assign": "off",
      "no-script-url": "off",
      "no-self-assign": "off",
      "no-self-compare": "off",
      "no-sequences": "off",
      "no-throw-literal": "off",
      "no-unmodified-loop-condition": "off",
      "no-unused-expressions": "off",
      "no-unused-labels": "off",
      "no-useless-call": "off",
      "no-useless-concat": "off",
      "no-useless-escape": "off",
      "no-void": "off",
      "no-warning-comments": "off",
      "no-with": "off",
      "radix": "off",
      "vars-on-top": "off",
      "wrap-iife": "off",
      "yoda": "off"
    }
  }
];

export default eslintConfig;
